### ISSUE TITLE
Better explanation of escrow and payments in docs

### ISSUE THREAD

**Issue by achow101** [ReinProject/python-rein#29]
Can there be a better explanation of the escrow addresses and the signed payments in the docs?

e.g. questions that might be asked.
Why are there two escrow addresses? How much go into each one?

What goes in the Signed Primary Payment and Signed mediator payment fields when accepting a job?

**Comment by bitspill** [comment]
2 Escrow addresses because there are two parties being paid. One address/payment goes to the mediator and one address/payment goes to the worker.

The signed payments are the redeem scripts from the earlier steps signed with coinb.in to complete 1of3 and after submission the other party can sign and broadcast to the network for 2of3 and get paid.

It's a little difficult to go into extreme detail via Github issues, feel free to email me rein@bitspill.net or find me on Freenode as bitspill.

Also, did you watch the getting started video series? It's a 4 part crash course on Rein operation https://www.youtube.com/playlist?list=PLIe7tQczGXJSCcXGUsLdbscTBZTxN5m9N

**Comment by weex** [comment]
We can definitely improve the explanations of those in the docs as well as in the process when someone is using the tool. Providing calculated values and a Bitcoin uri for the payments for example would probably make sense.

**Comment by weex** [comment]
Added info on addresses and payments to the Readme with 7d2aa051
